[package]
name = "examples-shared"
version = "0.1.0"
authors = ["4bb4 <67376761+4bb4@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
implot = { path = "../../" }
imgui = "0.6.0"
